
Namespace(root_path='kits19/data', list_dir='./lists_kits19', dataset='KiTS19', num_classes=3, max_iterations=30000, max_epochs=150, batch_size=4, n_gpu=1, deterministic=1, base_lr=0.0001, img_size=224, seed=42, n_skip=3, vit_name='R50-ViT-B_16', vit_patches_size=16, checkpoint_dir='./checkpoints_kits19', use_attention=0, exp='TU_KiTS19_224')
  0%|                                       | 0/30000 [01:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/train.py", line 86, in <module>
    trainer_kits19(args, net)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/trainer.py", line 264, in trainer_kits19
    loss, ce_loss, dice_loss = criterion(outputs, label_batch)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/trainer.py", line 62, in forward
    dice_loss = self.dice_loss(inputs, targets, softmax=softmax)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/trainer.py", line 40, in forward
    assert inputs.size() == targets.size()
AssertionError